"""Create, persist, and ensure Smite GRE tunnels (interface-agnostic)."""
from __future__ import annotations

import ipaddress
import json
import logging
import os
import re
import socket
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

logger = logging.getLogger(__name__)

DEFAULT_IFACE = "smite-gre"
DEFAULT_NETWORK = "172.17.1.0/30"
DEFAULT_MTU = 1472
CONFIG_DIR = Path(os.environ.get("SMITE_NODE_CONFIG", "/etc/smite-node"))
GRE_STATE_FILE = CONFIG_DIR / "gre.json"
GRE_UP_SCRIPT = CONFIG_DIR / "gre-up.sh"


def _run(cmd: list, timeout: int = 15) -> Tuple[int, str, str]:
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return proc.returncode, proc.stdout or "", proc.stderr or ""
    except Exception as e:
        return 1, "", str(e)


def detect_default_route() -> Dict[str, Optional[str]]:
    """
    Detect outbound NIC and source IP without hardcoding eth0.
    Uses `ip route get 1.1.1.1` (works with ens*, enp*, eth*, etc.).
    """
    code, out, _ = _run(["ip", "-4", "route", "get", "1.1.1.1"])
    if code != 0 or not out.strip():
        code, out, _ = _run(["ip", "-4", "route", "show", "default"])
    text = out.strip().splitlines()[0] if out.strip() else ""
    iface = None
    src = None
    m_dev = re.search(r"\bdev\s+(\S+)", text)
    m_src = re.search(r"\bsrc\s+(\S+)", text)
    if m_dev:
        iface = m_dev.group(1)
    if m_src:
        src = m_src.group(1)
    if not src and iface:
        code, addr_out, _ = _run(["ip", "-4", "-o", "addr", "show", "dev", iface])
        m = re.search(r"inet\s+([0-9.]+)/", addr_out)
        if m:
            src = m.group(1)
    return {"iface": iface, "src": src, "raw": text}


def detect_local_ip_toward(remote_ip: str) -> Optional[str]:
    """Best local address used to reach the GRE peer."""
    if remote_ip:
        code, out, _ = _run(["ip", "-4", "route", "get", remote_ip])
        if code == 0:
            m = re.search(r"\bsrc\s+(\S+)", out)
            if m:
                return m.group(1)
    return detect_default_route().get("src")


def inner_ips_for_role(role: str, network: str = DEFAULT_NETWORK) -> Tuple[str, str]:
    """
    Assign stable /30 inners:
      foreign → .1 (local), .2 (peer)
      iran    → .2 (local), .1 (peer)
    """
    net = ipaddress.ip_network(network, strict=False)
    hosts = [str(h) for h in net.hosts()]
    if len(hosts) < 2:
        raise ValueError(f"Network {network} must have at least 2 host addresses")
    foreign_ip, iran_ip = hosts[0], hosts[1]
    role = (role or "iran").lower()
    if role == "foreign":
        return foreign_ip, iran_ip
    return iran_ip, foreign_ip


def _write_persistence(cfg: Dict[str, Any]) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    GRE_STATE_FILE.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    script = f"""#!/bin/bash
# Auto-generated by Smite — bring up GRE after reboot
set -e
modprobe ip_gre 2>/dev/null || true
modprobe gre 2>/dev/null || true
IFACE="{cfg['iface']}"
LOCAL="{cfg['local_public']}"
REMOTE="{cfg['remote_public']}"
INNER="{cfg['local_inner']}"
PREFIX="{cfg['prefixlen']}"
MTU="{cfg['mtu']}"
if ip link show "$IFACE" >/dev/null 2>&1; then
  ip link del "$IFACE" 2>/dev/null || true
fi
ip tunnel add "$IFACE" mode gre remote "$REMOTE" local "$LOCAL" ttl 255
ip link set "$IFACE" mtu "$MTU" up
ip addr replace "$INNER/$PREFIX" dev "$IFACE"
"""
    GRE_UP_SCRIPT.write_text(script, encoding="utf-8")
    try:
        GRE_UP_SCRIPT.chmod(0o755)
    except Exception:
        pass


def install_host_systemd() -> bool:
    """Install systemd unit on host if writable (install script / privileged)."""
    unit_path = Path("/etc/systemd/system/smite-gre.service")
    if not GRE_UP_SCRIPT.exists():
        return False
    unit = f"""[Unit]
Description=Smite GRE tunnel
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={GRE_UP_SCRIPT}
ExecStop=/sbin/ip link del {DEFAULT_IFACE}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""
    try:
        unit_path.write_text(unit, encoding="utf-8")
        _run(["systemctl", "daemon-reload"])
        _run(["systemctl", "enable", "smite-gre.service"])
        return True
    except Exception as e:
        logger.debug(f"systemd unit not installed: {e}")
        return False


def _icmp_checksum(data: bytes) -> int:
    if len(data) % 2:
        data += b"\x00"
    total = 0
    for i in range(0, len(data), 2):
        total += (data[i] << 8) + data[i + 1]
        total = (total & 0xFFFF) + (total >> 16)
    return (~total) & 0xFFFF


def ping_df(host: str, payload: int, timeout: float = 1.0) -> str:
    """
    One DF ICMP echo. Returns ok, too_big, or fail.
    Ignores ICMP that is not this probe. Does not change any interface.
    """
    import struct
    import time

    payload = max(0, int(payload))
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)
    except OSError as e:
        return f"fail:{e}"
    try:
        # IP_MTU_DISCOVER / IP_PMTUDISC_DO — do not fragment.
        sock.setsockopt(socket.IPPROTO_IP, 10, 2)
        sock.settimeout(0.3)
        ident = os.getpid() & 0xFFFF
        seq = (payload ^ int(time.time() * 1000)) & 0xFFFF or 1
        data = b"S" * payload
        header = struct.pack("!BBHHH", 8, 0, 0, ident, seq)
        header = struct.pack("!BBHHH", 8, 0, _icmp_checksum(header + data), ident, seq)
        try:
            sock.sendto(header + data, (host, 0))
        except OSError as e:
            if getattr(e, "errno", None) in (90, 40):
                return "too_big"
            return "fail"
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            try:
                pkt, _addr = sock.recvfrom(4096)
            except socket.timeout:
                continue
            if not pkt:
                continue
            if pkt[0] in (0, 3, 8):
                icmp = pkt
            else:
                ihl = (pkt[0] & 0x0F) * 4
                icmp = pkt[ihl:] if len(pkt) > ihl else b""
            if len(icmp) < 8:
                continue
            if icmp[0] == 3 and icmp[1] == 4:
                return "too_big"
            if icmp[0] != 0:
                continue
            rid, rseq = struct.unpack("!HH", icmp[4:8])
            if rid == ident and rseq == seq:
                return "ok"
        return "fail"
    finally:
        sock.close()


def _classify_size(host: str, payload: int) -> str:
    """ok if the size fits at least once. too_big only on an explicit DF refusal."""
    saw_too_big = False
    for _ in range(2):
        result = ping_df(host, payload)
        if result == "ok":
            return "ok"
        if result == "too_big":
            saw_too_big = True
    return "too_big" if saw_too_big else "fail"


def discover_underlay_mtu(host: str) -> Dict[str, Any]:
    """
    Largest IPv4 packet (DF) that reaches host.
    ICMP payload + 28 = IP MTU. Does not modify GRE or tunnels.
    """
    host = (host or "").strip()
    if not host:
        return {"ok": False, "error": "Probe target is empty"}

    if _classify_size(host, 548) != "ok":
        return {"ok": False, "error": f"No ICMP reply from {host}. MTU was not changed."}

    # Common case: a 1500-byte path. One success is enough; do not shrink on loss.
    if _classify_size(host, 1472) == "ok":
        return {"ok": True, "host": host, "underlay_mtu": 1500, "payload": 1472, "steps": 1}

    lo, hi = 548, 1471
    best = 548
    steps = 1
    while lo <= hi and steps < 14:
        mid = (lo + hi) // 2
        steps += 1
        result = _classify_size(host, mid)
        if result == "ok":
            best = mid
            lo = mid + 1
        elif result == "too_big":
            hi = mid - 1
        else:
            # Loss is not a smaller MTU. Try the next smaller candidate once.
            hi = mid - 1

    if _classify_size(host, best) != "ok":
        return {"ok": False, "error": f"Probe to {host} was unstable. MTU was not changed."}

    return {
        "ok": True,
        "host": host,
        "underlay_mtu": best + 28,
        "payload": best,
        "steps": steps,
    }


def ensure_gre(
    remote_public_ip: str,
    role: str = "iran",
    local_public_ip: Optional[str] = None,
    local_inner: Optional[str] = None,
    peer_inner: Optional[str] = None,
    network: str = DEFAULT_NETWORK,
    iface: str = DEFAULT_IFACE,
    mtu: int = DEFAULT_MTU,
) -> Dict[str, Any]:
    """
    Create or recreate a GRE tunnel to remote_public_ip.
    Does not depend on eth0 — local public IP is auto-detected.
    """
    remote_public_ip = (remote_public_ip or "").strip()
    if not remote_public_ip:
        raise ValueError("remote_public_ip is required")

    local_public = (local_public_ip or "").strip() or detect_local_ip_toward(remote_public_ip)
    if not local_public:
        raise RuntimeError("Could not detect local public IP (no default route)")

    if local_inner and peer_inner:
        li, pi = local_inner.strip(), peer_inner.strip()
    else:
        li, pi = inner_ips_for_role(role, network)

    net = ipaddress.ip_network(network, strict=False)
    prefixlen = net.prefixlen
    mtu = int(mtu or DEFAULT_MTU)
    iface = (iface or DEFAULT_IFACE).strip() or DEFAULT_IFACE

    _run(["modprobe", "ip_gre"])
    _run(["modprobe", "gre"])

    code, link_out, _ = _run(["ip", "-d", "link", "show", iface])
    already = code == 0 and remote_public_ip in (link_out or "")
    if already:
        # Same GRE peer: only adjust MTU. Do not delete the tunnel.
        code, _, err = _run(["ip", "link", "set", iface, "mtu", str(mtu), "up"])
        if code != 0:
            raise RuntimeError(f"ip link set mtu failed: {err.strip()}")
        code, _, err = _run(["ip", "addr", "replace", f"{li}/{prefixlen}", "dev", iface])
        if code != 0:
            raise RuntimeError(f"ip addr replace failed: {err.strip()}")
    else:
        _run(["ip", "link", "del", iface])
        code, _, err = _run(
            [
                "ip", "tunnel", "add", iface,
                "mode", "gre",
                "remote", remote_public_ip,
                "local", local_public,
                "ttl", "255",
            ]
        )
        if code != 0:
            _run(["ip", "link", "del", iface])
            code, _, err = _run(
                [
                    "ip", "tunnel", "add", iface,
                    "mode", "gre",
                    "remote", remote_public_ip,
                    "local", local_public,
                    "ttl", "255",
                ]
            )
            if code != 0:
                raise RuntimeError(f"ip tunnel add failed: {err.strip()}")

        code, _, err = _run(["ip", "link", "set", iface, "mtu", str(mtu), "up"])
        if code != 0:
            raise RuntimeError(f"ip link set failed: {err.strip()}")

        code, _, err = _run(["ip", "addr", "replace", f"{li}/{prefixlen}", "dev", iface])
        if code != 0:
            raise RuntimeError(f"ip addr replace failed: {err.strip()}")

    # Loosen rp_filter on GRE for asymmetric paths
    for path in (
        f"/proc/sys/net/ipv4/conf/{iface}/rp_filter",
        "/proc/sys/net/ipv4/conf/all/rp_filter",
    ):
        try:
            Path(path).write_text("0")
        except Exception:
            pass

    cfg = {
        "iface": iface,
        "role": (role or "iran").lower(),
        "local_public": local_public,
        "remote_public": remote_public_ip,
        "local_inner": li,
        "peer_inner": pi,
        "network": str(net),
        "prefixlen": prefixlen,
        "mtu": mtu,
        "underlay_iface": detect_default_route().get("iface"),
    }
    _write_persistence(cfg)
    install_host_systemd()

    # Apply MSS helpers
    try:
        from app.network_optimize import ensure_mtu_optimizations, mss_for_mtu
        ensure_mtu_optimizations(path_mtu=mtu, mss=mss_for_mtu(mtu))
    except Exception as e:
        logger.warning(f"MSS after GRE skipped: {e}")

    logger.info(
        "GRE ready: %s local=%s remote=%s inner=%s peer=%s mtu=%s underlay=%s",
        iface, local_public, remote_public_ip, li, pi, mtu, cfg.get("underlay_iface"),
    )
    return {"status": "ok", "gre": cfg}


def ensure_gre_from_env() -> Optional[Dict[str, Any]]:
    """Bring up GRE from env vars or saved gre.json (node startup / install)."""
    peer = (os.environ.get("GRE_PEER_IP") or os.environ.get("GRE_REMOTE_IP") or "").strip()
    role = (os.environ.get("NODE_ROLE") or os.environ.get("GRE_ROLE") or "iran").strip()
    local = (os.environ.get("GRE_LOCAL_IP") or "").strip() or None
    local_inner = (os.environ.get("GRE_LOCAL_INNER") or "").strip() or None
    peer_inner = (os.environ.get("GRE_PEER_INNER") or "").strip() or None
    network = (os.environ.get("GRE_NETWORK") or DEFAULT_NETWORK).strip()
    iface = (os.environ.get("GRE_IFACE") or DEFAULT_IFACE).strip()
    mtu = int(os.environ.get("GRE_MTU") or DEFAULT_MTU)

    if not peer and GRE_STATE_FILE.exists():
        try:
            saved = json.loads(GRE_STATE_FILE.read_text(encoding="utf-8"))
            peer = saved.get("remote_public")
            role = saved.get("role") or role
            local = saved.get("local_public") or local
            local_inner = saved.get("local_inner") or local_inner
            peer_inner = saved.get("peer_inner") or peer_inner
            network = saved.get("network") or network
            iface = saved.get("iface") or iface
            mtu = int(saved.get("mtu") or mtu)
        except Exception as e:
            logger.warning(f"Failed to read {GRE_STATE_FILE}: {e}")

    if not peer:
        return None

    # Already up with correct remote?
    code, link_out, _ = _run(["ip", "-d", "link", "show", iface])
    if code == 0 and peer in link_out:
        code2, addr_out, _ = _run(["ip", "-4", "-o", "addr", "show", "dev", iface])
        if code2 == 0 and (local_inner or "") in addr_out:
            logger.info(f"GRE {iface} already up toward {peer}")
            return {
                "status": "ok",
                "gre": {
                    "iface": iface,
                    "role": role,
                    "remote_public": peer,
                    "local_public": local or detect_local_ip_toward(peer),
                    "local_inner": local_inner,
                    "peer_inner": peer_inner,
                    "mtu": mtu,
                },
                "already": True,
            }

    return ensure_gre(
        remote_public_ip=peer,
        role=role,
        local_public_ip=local,
        local_inner=local_inner,
        peer_inner=peer_inner,
        network=network,
        iface=iface,
        mtu=mtu,
    )


def gre_status() -> Dict[str, Any]:
    from app.network_optimize import discover_gre_peers
    peers = discover_gre_peers()
    saved = None
    if GRE_STATE_FILE.exists():
        try:
            saved = json.loads(GRE_STATE_FILE.read_text(encoding="utf-8"))
        except Exception:
            saved = None
    route = detect_default_route()
    return {
        "underlay": route,
        "saved": saved,
        "peers": peers,
    }
